option('png', type: 'boolean', value: true)
option('tiff', type: 'boolean', value: true)
option('jpeg', type: 'boolean', value: true)
option('builtin_loaders', type: 'string', value: 'none')
option('gtk_doc', type: 'boolean', value: false)
option('docs', type: 'boolean', value: false)
option('introspection', type: 'feature', value: 'disabled')
option('man', type: 'boolean', value: false)
option('relocatable', type: 'boolean', value: true)
option('native_windows_loaders', type: 'boolean', value: false)
option('installed_tests', type: 'boolean', value: false)
option('gio_sniffing', type: 'boolean', value: true)
